[package]
name = "rzrouter"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.9.2"
bytes = "1.12.1"
clap = { version = "4.6.6", features = ["derive"] }
fastrand = "2.5.0"
futures = "0.3.33"
num_cpus = "1.17.0"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_yml = "0.0.13"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", default-features = true, features = ["env-filter", "json", "time"] }
metrics = "0.24.3"
metrics-exporter-prometheus = "0.18.1"
axum = { version = "0.8.8", features = ["tokio", "http2"] }
axum-server = { version = "0.8.0" }

[dev-dependencies]
chrono = "0.4.45"
uuid = { version = "1.24.1", features = ["v4"] }
