# // SPDX-License-Identifier: BUSL-1.1
# // Copyright (c) 2026 M. Javani
# //
# // This file is part of rzrouter.
# //
# // Use of this software is governed by the Business Source License 1.1
# // included in the LICENSE file in the root of this repository.

blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://m-javani.github.io/roomzin-doc/
    about: Check the official documentation first
  - name: Roomzin Discussions
    url: https://github.com/m-javani/roomzin-quickstart/discussions
    about: Ask general questions and discuss the Roomzin ecosystem
  - name: Security Report
    url: mailto:mehdy.javany@gmail.com
    about: Report security vulnerabilities privately